### ISSUE TITLE
Cannot use the addon

### ISSUE THREAD

**Issue by savdev11** [ddev/ddev-varnish#19] opened 2023-02-08 14:36 UTC
Hello, i'm trying to install and use varnish on a ddev drupal 10 multisite environment. I launched ddev get ddev/ddev-varnish and
ddev restart and this was the output: `yaml: line 3: did not find expected node content
Failed to restart project: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-project docker-compose -f /home/user1/projects/project/.ddev/.ddev-docker-compose-base.yaml -f /home/user1/projects/project/.ddev/docker-compose.varnish-extras.yaml -f /home/user1/projects/project/.ddev/docker-compose.varnish.yaml config', action='[config]', err='exit status 15', stdout='', stderr='yaml: line 3: did not find expected node content'`.

docker-compose.varnish-extras.yaml's content:

```
#ddev-generated
# This is the second half of the trick that puts varnish "in front of" the web
# container, just by switching the names.
{{  := "ddev.site" }}
{{ if .DdevGlobalConfig.project_tld }}{{  = .DdevGlobalConfig.project_tld }}{{ end }}
{{ if .DdevProjectConfig.project_tld }}{{  = .DdevProjectConfig.project_tld }} {{ end }}
{{  := print "novarnish." .DdevProjectConfig.name "."   }}
{{  := print "."  ",novarnish." }}
{{ if .DdevProjectConfig.additional_hostnames }}
{{  = print  "," "novarnish." (.DdevProjectConfig.additional_hostnames | join ) "."  }}
{{ end }}
{{ if .DdevProjectConfig.additional_fqdns }}
{{  = print  "," "novarnish." ( .DdevProjectConfig.additional_fqdns | join ",novarnish." )   }}
{{ end }}
services:
  web:
    environment:
    - VIRTUAL_HOST={{  }}
```

**Comment by jedubois** [comment] 2023-02-08 14:55
@savdev11 , can you give us a bit more context on your configuration, e.g. what does your ddev config.yaml look like?

**Comment by savdev11** [comment] 2023-02-08 15:01
> @savdev11 , can you give us a bit more context on your configuration, e.g. what does your ddev config.yaml look like?

Sure,
config.yaml:

```
name: project
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
nodejs_version: "16"
```

config.multisite.yaml:
```
additional_hostnames:
  - roma
  - milano
hooks:
  post-start:
  - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS roma; GRANT ALL ON roma.* to 'db'@'%';"
    service: db
  - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS milano; GRANT ALL ON milano.* to 'db'@'%';"
    service: db
```
I installed a drupal 10 project and added this additional hostnames.

**Comment by jedubois** [comment] 2023-02-08 15:09
@jedubois, thanks for the additional info. I don't use multisite myself. Would you be able to give us steps to reproduce in a simple case along the lines of what I did here: https://github.com/ddev/ddev-varnish/issues/4#issue-1247996420 ?

**Comment by rfay** [comment] 2023-02-08 15:13
` - VIRTUAL_HOST={{  }}` is definitely not going to work. Line 4. 

Did you just now do the `ddev get drud/ddev-varnish` ?  Something must be wrong with the generation of the file in your case. If you can put up a repo that demonstrates this it should be solvable.

**Comment by savdev11** [comment] 2023-02-08 15:53
To reply to both comments:

I followed the steps described by the readme of [this repository](https://github.com/ddev/ddev-contrib/tree/master/recipes/drupal8-multisite) to create a multisite drupal 10 ddev project with multiple databases. I verified that everything was working as expected and then i went ahead and launched the commands `ddev get ddev/ddev-varnish` and `ddev restart`. This caused the output in the first comment of this issue.

@rfay i'm not sure what you mean: should i create a github repo with all my local files for you to explore?
@jedubois If you think it will be useful i can create a "steps to reproduce guide".

This project uses the additional_hostnames key. Could this be a related issue?
I'm not an expert in the yaml language features but was my docker-compose.varnish-extras.yaml correctly generated? it seems like variables (especially $project_tld) weren't replaced correctly.

**Comment by rfay** [comment] 2023-02-08 16:59
Yes, if you make a trivial github repo that demonstrates the problem it should be solvable. Just create a Drupal project with the drupal10 quickstart, turn it into multisite, add a good README that explains how to use it. Then show what happens. Then this becomes a solvable problem.

**Comment by savdev11** [comment] 2023-02-09 09:59
Hi, i made the [repo with the README](https://github.com/savdev11/ddev-varnish-error). Let me know if i missed something.

**Comment by rfay** [comment] 2023-02-09 15:44
@savdev11 I checked out your repo, and did a `ddev get drud/ddev-varnish` and it immediately corrected the problem you had. 

What ddev version are you using? `ddev --version` ?

I had your problem on `ddev start` so I did `ddev get drud/ddev-varnish` and there it was... fixed.

**Comment by savdev11** [comment] 2023-02-09 15:49
@rfay The ddev is version v1.19.3

**Comment by jedubois** [comment] 2023-02-09 15:56
> @rfay The ddev is version v1.19.3

@rfay , what's the general approach on version support? I think test and support on the latest version only makes sense to me.

**Comment by savdev11** [comment] 2023-02-09 16:30
I updated DDEV and it worked! Thanks a lot. The last issue i have is that the novarnish* urls work only for the main address (multisitetest.ddev.site) while they show an error for the others (503: No ddev back-end site available.
This is the ddev-router container: There is no back-end webserver at the URL you specified. You may want to use "ddev start" to start the site.).

**Comment by rfay** [comment] 2023-02-09 16:54
No wonder it didn't work with v1.19.3 :) 

Many add-ons that have specific requirements use `ddev debug capabilities | grep <item>` as a requirement. 

For example, 
https://github.com/ddev/ddev-platformsh/blob/f60d73f1d2e8e44d5ed30f721ad81b9ccac681bb/install.yaml#L17-L20

**Comment by jedubois** [comment] 2023-02-09 17:13
@savdev11 , moving the additional_hosts declaration to .ddev/config.yml did the trick for me. Don't think ddev reads config.multisite.yml file before the install for the add-on runs so it's not aware of the additional_hostnames in that file. 

Having the additional_hostnames in config.yml shouldn't be a problem for your multisites.

**Comment by jedubois** [comment] 2023-02-09 17:36
> No wonder it didn't work with v1.19.3 :)
> 
> Many add-ons that have specific requirements use `ddev debug capabilities | grep <item>` as a requirement.
> 
> For example, https://github.com/ddev/ddev-platformsh/blob/f60d73f1d2e8e44d5ed30f721ad81b9ccac681bb/install.yaml#L17-L20

@rfay , ddev-get-yaml-interpolation and v1.19.4+ should do the trick?

**Comment by rfay** [comment] 2023-02-09 17:40
II thought that got introduced in v1.21.3 or something. But with the capabilities, the version is not relevant. 

However, this pipe technique doesn't work on Windows PowerShell. Should be OK for the vast majority of people. It needs some improvement.

**Comment by jedubois** [comment] 2023-02-09 17:49
Looks like v1.19.4 based on https://github.com/drud/ddev/blob/2613f3da465186bc70aacee3c8e80bf685a650fe/cmd/ddev/cmd/debug-capabilities.go

Added very simple check as per your example. PowerShell is outside my wheelhouse.

**Comment by jedubois** [comment] 2023-02-09 17:54
Ideally I should test this on an old version of DDEV. Any suggestions on the quickest way to do that? Gitpod maybe?

**Comment by rfay** [comment] 2023-02-09 17:56
https://ddev.readthedocs.io/en/latest/users/usage/faq/#how-can-i-install-a-specific-version-of-ddev

**Comment by jedubois** [comment] 2023-02-09 17:59
And that's pretty safe / I won't mess up my other projects if I keep 'em off?

**Comment by rfay** [comment] 2023-02-09 18:01
It won't mess up your other projects anyway. You just have to manage the $PATH or whatever your technique. "ddev" is just a single binary, not a set of libraries or anything. And each ddev binary specifies its own docker images.

**Comment by jedubois** [comment] 2023-02-09 18:12
@savdev11 , we've added a capability check so the add-on. Have you managed to get your set up working with adjustments to config.yml?

**Comment by rfay** [comment] 2023-03-01 23:43
I think it was right to close this, and it wouldn't have worked with older versions. Closing again. @savdev11 if you want to continue conversation, just speak up!

**Closed by rfay** 2023-03-01 23:43 UTC
